# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.4 MB 16.5 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.4 MB 16.4 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.4 MB 13.9 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 12.9 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.4 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 11.6 MB/s  0:00:01


### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [2]:
!pip install pandas
!pip install matplotlib
!pip install networkx
!pip install geopandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.8 MB 12.0 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.8 MB 16.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.8 MB 13.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 12.0 MB/s  0:00:00

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -----------

### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [4]:
import numpy as np
a = np.array([2, 4,6,8])
print(a+3)
print(2 * a)
print(a ** 2)
print(a -1)



[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [24]:
import numpy as np
import math

In [26]:

def g(h):
    return (f(x+h) - f(x)) / h  
G = np.vectorize(g)
def f(x):
    return math.sin(x)
h = np.linspace(-1,-4,4)
x = math.pi/2
vectf = map(g,10**h)
list(vectf)



[np.float64(-0.049958347219742905),
 np.float64(-0.004999958333473664),
 np.float64(-0.0004999999583255033),
 np.float64(-4.999999969612645e-05)]

###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [27]:
contlistA = np.array([2,1,3,4])
matrixA = contlistA.reshape(2,2)
contlistb = np.array([5,2,1,6])
matrixb = contlistb.reshape(2,2)
print (matrixA * matrixb)

[[10  2]
 [ 3 24]]
